[tool.black]
line-length=120
target-version=['py36']

[tool.isort]
line_length = 120
multi_line_output = 3
force_alphabetical_sort_within_sections = "True"
force_sort_within_sections = "False"
profile = "black"

[tool.mypy]
python_version = "3.6"
ignore_missing_imports = "True"

[[tool.mypy.overrides]]
module = "requests.*"
ignore_missing_imports = "True"
